### ISSUE TITLE
installation command is quite confusing

### ISSUE THREAD

**Issue by acpmasquerade** [ludbek/bro#15]
```
$ curl -o  /tmp/bro https://raw.githubusercontent.com/ludbek/bro/master/install && sh /tmp/bro
  BRO_STATION? ($HOME/.bro):         # directory where Bro will be installed
  WORKSTATION? ($HOME/projects):     # directory where Bro will store projects
$ source ~/.bashrc
```
the two lines were supposed to be prompts for inputs.

**Comment by ludbek** [comment]
I have updated the readme file. Hope its better than before :)

**Comment by acpmasquerade** [comment]
WORKSTATION constant might be conflicting at times. 

like BRO_STATION, what about BRO_WORKSTATION ?

**Comment by ludbek** [comment]
I think `BRO_PROJECTS_DIR` better. Closing this issue for now.
