### ISSUE TITLE
sequencing of tasks is required

### ISSUE THREAD

**Issue by bewakes** [ludbek/bro#30]
It should have a feature of sequencing tasks like:
bro <project name> task1 task2 task3 ...
which will have effect of initializing project and then calling the tasks

**Comment by ludbek** [comment]
This convention won't work for tasks which takes arguments. It would be better to compose tasks inside a function.

`bro` command is available within a task. Which means it can be used in following ways:

```shell
task3 () {
     bro task2
     bro task3
     # ... some custom stuff
}
```

Hope this meets your need.

**Comment by bewakes** [comment]
Yeah, that works.
