### ISSUE TITLE
I found it similar to fabric

### ISSUE THREAD

**Issue by acpmasquerade** [ludbek/bro#4]
I found it similar to `fabric`. Besides that `fabric` is much powerful in executing remote commands also grouped with category of the machine you want to execute the command. Anything specific that you feel your implementation is easier / better ?

**Comment by ludbek** [comment]
I don't have much experience with `fabric` but I believe its inclined to project deployment. `bro` is specifically designed for project management i.e. project creation based upon pre-built templates, quicker way to jump to project directory, activate project environment and custom light tasks. Also, its a generic tool for managing projects of any programming language. I have been using `bro` for projects in languages like `python, javascript, clojure, etc` to name few.

**Comment by ludbek** [comment]
Since this is not exactly an issue, m closing this :)
